### PR TITLE
Add config option for executable path

### LINKED ISSUE #1: Expose config option for executable path
It looks like there is a config option `genealabs.phpcs.executablePath` in main.js, but it is not exposed in the UI.

### PR DESCRIPTION
**Pull request by davisben**
Resolves #1

### CODE REVIEW

**Comment by mikebronner** [comment]
Hi @davisben, thanks so much for submitting this PR! I actually had this in place, but temporarily removed it as I was researching some issues. I'll go ahead and add it back in. Closing this PR, as I already have the code.

**Comment by mikebronner** [comment]
@davisben just FYI: I have pushed a few new version since yesterday, one of which includes this feature. Let me know how it works for you. :) Thanks again for submitting the issue and PR!

**Comment by davisben** [comment]
Looks good here. Thanks for your work on this!

**Comment by mikebronner** [comment]
That's awesome! Thanks for the feedback. Out of curiosity, what is your use-case for needing to customize the executable? (The only reason I currently need to customize it is to load a custom `CodeSniffer.conf` file.) I'm eager to learn of other use-cases that I can keep in mind while improving functionality.

Thanks!
~Mike

**Comment by davisben** [comment]
I have some standards installed by composer that weren't being found by the included executable, so by setting the path to the phpcs executable in vendor/bin, those standards were found.

**Comment by mikebronner** [comment]
Ah, yes! I'm doing the same. Was thinking of letting the user provide a path to their `CodeSniffer.conf` standards file and let it load that one, regardless of where PHPCS is installed. Still working on that. :)

**Pull request closed without merging**
